[libraries]
google-oauth-client = { module = "com.google.oauth-client:google-oauth-client-jetty", version = "1.36.0" }
google-api-directory = { module = "com.google.apis:google-api-services-admin-directory", version = "directory_v1-rev20240924-2.0.0" }
apache-commons-collections = { module = "org.apache.commons:commons-collections4", version = "4.4" }
# For getting rid of annotation warnings
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version = "4.8.6" }
bnd-annotation = { module = "biz.aQute.bnd:biz.aQute.bnd.annotation", version = "7.0.0" }
osgi-annotation = { module = "org.osgi:osgi.annotation", version = "8.1.0" }

[plugins]
springboot = { id = "org.springframework.boot", version = "3.3.3" }
tasktree = { id = "com.dorongold.task-tree", version = "4.0.0" }