[versions]
resilience4j = "2.3.0"
checkerframework = "3.49.4"

[libraries]
google-oauth-client = { module = "com.google.oauth-client:google-oauth-client-jetty", version = "1.39.0" }
google-api-directory = { module = "com.google.apis:google-api-services-admin-directory", version = "directory_v1-rev20250916-2.0.0" }
apache-commons-collections = { module = "org.apache.commons:commons-collections4", version = "4.5.0" }
otel-logs-autoconfigure = { module = "am.ik.spring.opentelemetry:otel-logs-autoconfigure", version = "0.3.0" }
resilience4j-ratelimiter = { module = "io.github.resilience4j:resilience4j-ratelimiter", version.ref = "resilience4j" }
checker-main = { module = "org.checkerframework:checker", version.ref = "checkerframework" }
checker-util = { module = "org.checkerframework:checker-util", version.ref = "checkerframework" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
# For getting rid of annotation warnings
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version = "4.9.3" }
bnd-annotation = { module = "biz.aQute.bnd:biz.aQute.bnd.annotation", version = "7.1.0" }
osgi-annotation = { module = "org.osgi:osgi.annotation", version = "8.1.0" }

[plugins]
springboot = { id = "org.springframework.boot", version = "3.5.3" }
tasktree = { id = "com.dorongold.task-tree", version = "4.0.1" }
cyclonedx = { id = "org.cyclonedx.bom", version = "2.3.1" }
checkerframework = { id = "org.checkerframework", version = "0.6.55" }
