# Build workflow

name: CI

on:
  push:
    branches:
      - main
      - 'support/v*'
    tags:
      - v* # Also version tags

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write # For the container
      contents: write # For the dependency graph
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          submodules: 'recursive'

      - name: Verify Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build
        run: ./gradlew build -Pchecker=true -Pstrict=true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=main
            # branch name, except main, which gets the edge label
            type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            # full version
            #type=semver,pattern={{version}}
            # minor version
            #type=semver,pattern={{major}}.{{minor}}
            # major version
            #type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
