name: Submit Dependency Graph

on:
  workflow_run:
    workflows: ['Generate Dependency Graph']
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  submit-dependency-graph:
    name: Submit dependency graph
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: download-and-submit # Download saved dependency-graph and submit
